name: ont_assembly
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - porechop==0.2.4
  - nanoplot==1.42.0
  - filtlong==0.2.1
  - necat==0.0.1_update20200803
  - minimap2==2.28
  - racon==1.5.0
  - medaka==1.11.3
  - busco==5.7.1
  - gfastats==1.3.6
